### ISSUE TITLE
Not working with Expo SDK 52

### ISSUE THREAD

**Issue by saimon24** [drizzle-team/drizzle-studio-expo#4]
This plugin doesn't work with Expo SDK 52 and the New Arch enabled.

The Expo-SQLite package might have changed, as the hook throws an incorrect type error:
![Screenshot 2024-11-04 at 13 11 25](https://github.com/user-attachments/assets/4847b91a-072e-491b-9183-81092637e883)

You can still open the dev tools, but apparently, there is only an empty view and no logs.
![Screenshot 2024-11-04 at 13 11 57](https://github.com/user-attachments/assets/b516c5c0-40b9-4b54-8c2d-37691481d0b9)

What can we do to fix this? Maybe updating expo-sqlite to the current 15.0.1 could fix this?

**Comment by raulval** [comment]
Same here

**Comment by arscslvt** [comment]
Same, using SDK 52. I was getting crazy cause of no logs about it.

**Comment by Thomsr** [comment]
I am facing the same issue with Expo SDK 52 now being the standard in the expo go app.

**Comment by ecanakci** [comment]
Same error on SDK 52

**Comment by ax-vasquez** [comment]
Getting this error as well after updating; everything else is good to go after migrating to Expo 52.

The "meat and potatoes" of the error I am seeing seems to be:

> `Property 'databaseName' is missing in type 'import("<REPO_ROOT>/node_modules/expo-sqlite/build/SQLiteDatabase").SQLiteDatabase', but required in type 'import("<REPO_ROOT>/node_modules/expo-drizzle-studio-plugin/node_modules/expo-sqlite/build/SQLiteDatabase").SQLiteDatabase'`

It looks like the package of `expo-sqlite` needs to be updated in `expo-drizzle-studio-plugin`

**Comment by ax-vasquez** [comment]
I dug into this some more today and got a fix in place; just waiting on review/merging!

Here is the PR that should fix this issue (I've tested it locally and seen the studio working):

https://github.com/drizzle-team/drizzle-studio-expo/pull/5

You can test it by cloning the branch and running `npm run pack`, then use the resulting `*.tgz` file as the version for `drizzle-studio-expo` in your Expo 52 project (set the version to `file:<file_name>.tgz`)

**Comment by Kyrylo-Usichenko** [comment]
Plugin is updated to be compatible with Expo v52. 
Thanks, @ax-vasquez!

**Comment by ax-vasquez** [comment]
No problem - happy to help! 🙂 

Awesome! Just installed version `0.1.0` and I'm back in business - thanks for the quick response, @Kyrylo-Usichenko ! 🙏

**Comment by Thommyaso** [comment]
Hi, I know the issue is now closed, but I'm still getting an empty page. Any Idea why it could be? Using SDK 52, version of the plugin 0.1.1. No errors showing up in the console. Thanks

**Comment by jluisrojas** [comment]
Same! I'm still getting an empty page on plugin 0.1.1

**Comment by Cratis1831** [comment]
I am also receiving the blank screen using expo sdk 52 and prebuilt

**Comment by azeezolaniran2016** [comment]
I'm also getting this blank screen on Expo SDK 52.0.25.

**Comment by Sholamide** [comment]
> I'm also getting this blank screen on Expo SDK 52.0.25.

Did you fix this yet? It's showing blank screen for me too. @saimon24 @ax-vasquez  FYI

**Comment by aaronksaunders** [comment]
I was passing the wrong database variable in, you need to pass in the SQLite db, not the db from drizzle.

**Comment by DatMoser** [comment]
Same here. 
Personally think it might be related to the new react-native architecture, introduced in expo sdk 52 and also mentioned in #7 
Additionally, I run into errors that useDrizzleStudio(db) requires the property "databaseName" which does not exist in expo-sqlite.SQLiteDatabase 👀

Really think this issue should be at least reopened

**Comment by JaredCowgill** [comment]
I was also experiencing the same issue for a while, I actually got it to fix by just refreshing the page haha. I think the issue is that my migrations weren't running until after I was calling the drizzlestudio hook in my app so it just didn't exist yet. So once I actually tried making a change in the database and then refreshed the page it worked.

**Comment by 930r91na** [comment]
I am in 52.0.4, correctly using SQLite db and receiving and sending data

![Image](https://github.com/user-attachments/assets/20246670-f4d0-491f-bb67-584ce2c3428e)

Nevertheless is still stuck in the loading of the broadcast

**Comment by blackirishmec** [comment]
> I was passing the wrong database variable in, you need to pass in the SQLite db, not the db from drizzle.

You are a legend, thank you @aaronksaunders !!!

**Comment by eNiiju** [comment]
I get the same issue with expo 53 (53.0.7). Infinite loading in the browser. Using expo-drizzle-studio-plugin 0.1.2

**Comment by mmarvelous078** [comment]
> I am in 52.0.4, correctly using SQLite db and receiving and sending data
> 
> ![Image](https://github.com/user-attachments/assets/20246670-f4d0-491f-bb67-584ce2c3428e)
> 
> Nevertheless is still stuck in the loading of the broadcast

Did you find a solution?
