### ISSUE TITLE
Studio presents an empty page on all browsers

### ISSUE THREAD

**Issue by danb4r** [drizzle-team/drizzle-studio-expo#7]
![image](https://github.com/user-attachments/assets/97eb141f-c161-4b10-87fb-65b3dd3032ee)

As other users reported at the end of the #4 thread, the plugin is presenting an empty page to the user. I've tested with Chrome, Edge, Brave and Firefox with the same response as the picture above.

Expo doctor did not report any issues with dependencies in my project. I followed the instructions in the README.

This is my expo-info:

  expo-env-info 1.2.1 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.20.4 - ~\AppData\Local\fnm_multishells\39820_1733703331795\node.EXE
      npm: 10.9.0 - ~\AppData\Local\fnm_multishells\39820_1733703331795\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 34, 35
        Build Tools: 34.0.0, 35.0.0
        System Images: android-24 | Google Play Intel x86 Atom, android-35 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: AI-242.23339.11.2421.12550806
    npmPackages:
      babel-preset-expo: ~11.0.0 => 11.0.15 
      expo: ~51.0.39 => 51.0.39 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.6 => 0.19.12 
    Expo Workflow: bare

**Comment by devethan** [comment]
In my case, "crypto.randomUUID is not a function" error shown on console. Same on Chrome, Brave.
I think it is because of that some of dependencies are using `window.crypto` module which is not supported on Http protocol.

**Comment by danb4r** [comment]
> As other users reported at the end of the #4 thread, the plugin is presenting an empty page to the user. I've tested with Chrome, Edge, Brave and Firefox with the same response as the picture above.
> 
> Expo doctor did not report any issues with dependencies in my project. I followed the instructions in the README.

I would like to add that there is no error presented in the expo console neither in the Android Studio Logcat for me.

**Comment by icastillejogomez** [comment]
Same here! White screen, no network or console errors

**Comment by pmk1c** [comment]
> In my case, "crypto.randomUUID is not a function" error shown on console. Same on Chrome, Brave.

I had the same error, but then I realized it was coming from a 1Password extensions. So this does not seem to be related (at least in my case). Deactivating the extension made the error disappear.

Now I have a blank screen without any error...

**Comment by florentmsl** [comment]
I’m experiencing the same issue.  When I open the app, the browser displays an empty page with a small loading spinner in the center. There are no network errors or console errors, but after a few seconds, I encounter an error in the terminal when I open the tools: `[TypeError: db.prepareAsync is not a function (it is undefined)]`. Has anyone else encountered this issue?

Versions:
* "expo": "~52.0.11",
* "expo-drizzle-studio-plugin": "^0.1.1",
* "drizzle-orm": "^0.38.2",
* "drizzle-kit": "^0.30.1"

**Comment by babucarr32** [comment]
Make sure `useDrizzleStudio` is using your actual database.
```
import { useDrizzleStudio } from "expo-drizzle-studio-plugin";
import * as SQLite from "expo-sqlite";
import { View } from "react-native";

const actualDatabse = SQLite.openDatabaseSync("db");

export default function App() {
    useDrizzleStudio(actualDatabse);

    return <View></View>;
}
```

**Comment by florentmsl** [comment]
> Make sure `useDrizzleStudio` is using your actual database.
> 
> ```
> import { useDrizzleStudio } from "expo-drizzle-studio-plugin";
> import * as SQLite from "expo-sqlite";
> import { View } from "react-native";
> 
> const actualDatabse = SQLite.openDatabaseSync("db");
> 
> export default function App() {
>     useDrizzleStudio(actualDatabse);
> 
>     return <View></View>;
> }
> ```

That was it! Thanks! I did use `const db = drizzle(sqlite);` with `useDrizzleStudio` instead of directly using the `sqlite` object

**Comment by danb4r** [comment]
> Make sure `useDrizzleStudio` is using your actual database.

Perfect! Thank you. As @florentmsl mentioned, I was also using drizzle(actualDatabase, ...) as the wronge source to studio.

**Comment by LoganRupe** [comment]
> pmk

I'm getting the same.  A blank screen without any error, or almost blank, it has the tiniest spinner. No errors anywhere and no data returned from ws network.

**Comment by danb4r** [comment]
> > pmk
> 
> I'm getting the same. A blank screen without any error, or almost blank, it has the tiniest spinner. No errors anywhere and no data returned from ws network.

Did you see @florentmsl solution?

This is the right way, passing the SQLite db straight to ```useDrizzleStudio```:

```js
const actualDatabse = SQLite.openDatabaseSync("db");
```

Not this one:

```js
const expoSqlite = SQLite.openDatabaseSync("db");
const wrongDatabase= drizzle(expoSqlite, { schema: schema.default });
```

**Comment by LoganRupe** [comment]
> > > pmk
> > 
> > 
> > I'm getting the same. A blank screen without any error, or almost blank, it has the tiniest spinner. No errors anywhere and no data returned from ws network.
> 
> Did you see @florentmsl solution?
> 
> This is the right way, passing the SQLite db straight to `useDrizzleStudio`:
> 
> ```js
> const actualDatabse = SQLite.openDatabaseSync("db");
> ```
> 
> Not this one:
> 
> ```js
> const expoSqlite = SQLite.openDatabaseSync("db");
> const wrongDatabase= drizzle(expoSqlite, { schema: schema.default });
> ```

Yes, I tried that and unfortunately it did not resolve my issue. I'm afk today but will work on a minimal repro tomorrow and link. Sorry.

**Comment by babucarr32** [comment]
> > > > pmk
> > > 
> > > 
> > > I'm getting the same. A blank screen without any error, or almost blank, it has the tiniest spinner. No errors anywhere and no data returned from ws network.
> > 
> > 
> > Did you see @florentmsl solution?
> > This is the right way, passing the SQLite db straight to `useDrizzleStudio`:
> > ```js
> > const actualDatabse = SQLite.openDatabaseSync("db");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not this one:
> > ```js
> > const expoSqlite = SQLite.openDatabaseSync("db");
> > const wrongDatabase= drizzle(expoSqlite, { schema: schema.default });
> > ```
> 
> Yes, I tried that and unfortunately it did not resolve my issue. I'm afk today but will work on a minimal repro tomorrow and link. Sorry.

No worries, we all need help at some point. You can share the repro.

**Comment by LoganRupe** [comment]
> > > 
> > > Did you see @florentmsl solution?
> > > This is the right way, passing the SQLite db straight to `useDrizzleStudio`:
> > > ```js
> > > const actualDatabse = SQLite.openDatabaseSync("db");
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Not this one:
> > > ```js
> > > const expoSqlite = SQLite.openDatabaseSync("db");
> > > const wrongDatabase= drizzle(expoSqlite, { schema: schema.default });
> > > ```
> > 
> > 
> > Yes, I tried that and unfortunately it did not resolve my issue. I'm afk today but will work on a minimal repro tomorrow and link. Sorry.
> 
> No worries, we all need help at some point. You can share the repro.
> >
I managed to resolve the issue through the creation on a minimal reproduction.

The issue for me ended up being that I need to upgrade to `expo@52` and set `newArchEnabled=true` in `app.json`.
Anyway, the minimal reproduction is working correctly here: https://github.com/LoganRupe/drizzle-rnr-min-repro
Also, it took a while for the loading icon to disappear on load (my machine is probably slow or schema is large) but it WORKS! 🎉 

Thanks for your time.

**Comment by babucarr32** [comment]
> > > > Did you see @florentmsl solution?
> > > > This is the right way, passing the SQLite db straight to `useDrizzleStudio`:
> > > > ```js
> > > > const actualDatabse = SQLite.openDatabaseSync("db");
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Not this one:
> > > > ```js
> > > > const expoSqlite = SQLite.openDatabaseSync("db");
> > > > const wrongDatabase= drizzle(expoSqlite, { schema: schema.default });
> > > > ```
> > > 
> > > 
> > > Yes, I tried that and unfortunately it did not resolve my issue. I'm afk today but will work on a minimal repro tomorrow and link. Sorry.
> > 
> > 
> > No worries, we all need help at some point. You can share the repro.
> > >
> 
> I managed to resolve the issue through the creation on a minimal reproduction.
> 
> The issue for me ended up being that I need to upgrade to `expo@52` and set `newArchEnabled=true` in `app.json`. Anyway, the minimal reproduction is working correctly here: https://github.com/LoganRupe/drizzle-rnr-min-repro Also, it took a while for the loading icon to disappear on load (my machine is probably slow or schema is large) but it WORKS! 🎉
> 
> Thanks for your time.

You are welcome.

**Comment by icastillejogomez** [comment]
In my case, the problem is a that I have a system to manage the database and a hook to provide the database like this:

```ts
...
import { useDrizzleStudio } from 'expo-drizzle-studio-plugin';
...

export default function App() {
  const db = useDb();
  useDrizzleStudio(db);
  
  return (
    ...
  )
}
```

And my custom hook returns `null` at the first time and because in this line the `useEffect` dependencies don't contain the `db` the listener is not set again propertly.

https://github.com/drizzle-team/drizzle-studio-expo/blob/adb0167c2521d81c4110b79d7d8b23013e7ef206/src/useDrizzleStudio.tsx#L41

**Comment by icastillejogomez** [comment]
I just opened this PR to offer a possible fix for this issue: https://github.com/drizzle-team/drizzle-studio-expo/pull/8

**Comment by samhornstein** [comment]
> > > > Did you see @florentmsl solution?
> > > > This is the right way, passing the SQLite db straight to `useDrizzleStudio`:
> > > > ```js
> > > > const actualDatabse = SQLite.openDatabaseSync("db");
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Not this one:
> > > > ```js
> > > > const expoSqlite = SQLite.openDatabaseSync("db");
> > > > const wrongDatabase= drizzle(expoSqlite, { schema: schema.default });
> > > > ```
> > > 
> > > 
> > > Yes, I tried that and unfortunately it did not resolve my issue. I'm afk today but will work on a minimal repro tomorrow and link. Sorry.
> > 
> > 
> > No worries, we all need help at some point. You can share the repro.
> > >
> 
> I managed to resolve the issue through the creation on a minimal reproduction.
> 
> The issue for me ended up being that I need to upgrade to `expo@52` and set `newArchEnabled=true` in `app.json`. Anyway, the minimal reproduction is working correctly here: https://github.com/LoganRupe/drizzle-rnr-min-repro Also, it took a while for the loading icon to disappear on load (my machine is probably slow or schema is large) but it WORKS! 🎉
> 
> Thanks for your time.

Thanks, I ran into this same issue and your solution resolved it for me. Unfortunately, `npx expo run:ios` fails after running `npm install expo@52`. Running `npx install-expo-modules@latest` as per this comment (https://github.com/expo/expo/issues/15959#issuecomment-1423697799)  reverts back to `expo@51` and resolves the build error but of course Drizzle Studio doesn't load unless I run `npm install expo@52` again after building.

**Comment by Al-Plum** [comment]
Had the same problem with a blank screen but have it working now.
Took me a bit to figure it out that I had actually called my database **reports** and not **db**. 


```javascript
import { StyleSheet, Text, View } from "react-native";
import React from "react";
import { Drawer } from "expo-router/drawer";
import { GestureHandlerRootView } from "react-native-gesture-handler";
import { useDrizzleStudio } from "expo-drizzle-studio-plugin";
import * as SQLite from "expo-sqlite";

const reports = SQLite.openDatabaseSync("reports.db"); 
//My database is called reports

const Layout = () => {
  useDrizzleStudio(reports);
  return (
    <GestureHandlerRootView>
      <Drawer
        screenOptions={{
```

**Comment by RobertoJoseph** [comment]
Still having the same issue
"expo-drizzle-studio-plugin": "^0.1.1",
 "expo-sqlite": "~14.0.6",
  "expo": "~51.0.28",
  
  Any help?

**Comment by sobi916** [comment]
I have experienced the same issue but resolved it like this:-
  
```
const [db, setDb] = useState<SQLite.SQLiteDatabase | null>(null);

  useDrizzleStudio(db);

  useEffect(() => {
    const initializeDatabase = async () => {
      try {
        const db = await SQLite.openDatabaseAsync('databaseName');
        setDb(db);
        console.log('Database opened successfully', db);
      } catch (error) {
        console.error('Error opening database:', error);
      }
    };

    initializeDatabase();
  }, []);
```

**Comment by jamie0xgitc0decat** [comment]
```
export const expoDb = openDatabaseSync(DATABASE_NAME);
export const db = drizzle(expoDb);

```


for me is resovled by using expoDb not db

**Comment by 930r91na** [comment]
I use sqlite db, wait until migration is completed and so. And receive an send data but still it is stuck in loading screen. Could anyone help me
Expo 52.0.41 

![Image](https://github.com/user-attachments/assets/99e60b9b-042e-4141-b781-879cb75039c6)

**Comment by laurentlouk** [comment]
> I use sqlite db, wait until migration is completed and so. And receive an send data but still it is stuck in loading screen. Could anyone help me Expo 52.0.41
> 
> ![Image](https://github.com/user-attachments/assets/99e60b9b-042e-4141-b781-879cb75039c6)

same for me, I could not change anything to make it work 😅 also using prebuild (nothing fansy, just regular prebuild)

**Comment by yilinjuang** [comment]
<img width="566" alt="Image" src="https://github.com/user-attachments/assets/323185d4-288d-47a7-86a3-44ca1b0e2a83" />

Same here. I can see data received in broadcast socket, but it's forever stuck in the loading state.

**Comment by carlosharrycrf** [comment]
I was able to get this working by updating expo. `npx expo install expo@latest` then `npx expo install --fix`.

**Comment by Lachcim13** [comment]
Updating from expo 52.0.41 to 52.0.44 and running `npx expo install --fix`  fixed the issue.

**Comment by 930r91na** [comment]
> Updating from expo 52.0.41 to 52.0.44 and running `npx expo install --fix` fixed the issue.

That worked, Thanks

**Comment by LovesWorking** [comment]
Worked once I placed the useDrizzleStudio where I create my context for react query :) Thanks everyone!

**Comment by bbalan** [comment]
This was happening to me because I was calling `useDrizzleStudio(db)` before the db had been initialized. I moved the hook call to a component that only renders after the db is initialized, and it worked.

**Comment by laurentlouk** [comment]
Problem fixed 👍🏻

**Comment by vzanfelici** [comment]
Hello!
I'm also having this error. Has anyone managed to fix it in version 53?

expo: 53.0.8
expo-drizzle-studio-plugin: 0.1.2
expo-sqlite: 15.2.9

**Comment by mon7792** [comment]
Hi 👋

I’m encountering same issue.Studio page in the browser appears empty. I've tried running the app using both `expo go` and `prebuild`, but the issue persists.

### **Environment Details**

Here are the package versions I'm using:

```json
"expo": "^53.0.9",  
"expo-sqlite": "~15.2.9",  
"drizzle-orm": "^0.43.1",  
"expo-drizzle-studio-plugin": "0.1.1"  
```

### **Help Needed**

Could anyone guide me toward a solution or suggest which part of my setup might be causing this problem? I'd also appreciate any debugging tips to investigate further myself.

Any insights on what might be going wrong ?

### **Current Workaround**

I’m currently developing on an iOS simulator. As a temporary workaround, I’ve been accessing the SQLite database directly on my host machine using a client like DBeaver.

To locate the database file, I use the following demo component:

```tsx
export const SQLPath = () => {  
  const db = useSQLiteContext();  
  useDrizzleStudio(db);  
  return (  
    <View>  
      <Text>SQLPath</Text>  
      <Text>{db.databasePath}</Text>  
    </View>  
  );  
};
```

This provides the database file path, which in my case looks like:

```
/Users/mon7792/Library/Developer/CoreSimulator/Devices/B6DF9CA3-5C55-42E9-B48A-97868E3F29D3/data/Containers/Data/Application/CF263091-7E2B-49D1-81F8-DAECB0A38158/Documents/ExponentExperienceData/@anonymous/tracker-87dd6509-83d1-45ac-a205-5c99757457fa/SQLite/*.db  
```

Thanks in advance! 😊

**Comment by vzanfelici** [comment]
Hello @mon7792 
On a macos when I display the db.databasePath it returns me an invalid path to put in the dbeaver. Do you know if there is another path that works for macos?

```const db = useSQLiteContext();
const drizzleDb = drizzle(db, { schema });
useDrizzleStudio(db);
console.log(db.databasePath)
```

` LOG  /data/data/host.exp.exponent/files/SQLite/db.db`

<img width="571" alt="Image" src="https://github.com/user-attachments/assets/250f926a-6d65-43e0-8686-3970b88b12e4" />

Or am I doing it wrong?

**Comment by mon7792** [comment]
> Hello [@mon7792](https://github.com/mon7792) On a macos when I display the db.databasePath it returns me an invalid path to put in the dbeaver. Do you know if there is another path that works for macos?
> 
> ```
> const drizzleDb = drizzle(db, { schema });
> useDrizzleStudio(db);
> console.log(db.databasePath)
> ```
> 
> ` LOG /data/data/host.exp.exponent/files/SQLite/db.db`
> 
> <img alt="Image" width="571" src="https://private-user-images.githubusercontent.com/86609742/442731955-250f926a-6d65-43e0-8686-3970b88b12e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDcwNTUzODQsIm5iZiI6MTc0NzA1NTA4NCwicGF0aCI6Ii84NjYwOTc0Mi80NDI3MzE5NTUtMjUwZjkyNmEtNmQ2NS00M2UwLTg2ODYtMzk3MGI4OGIxMmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTEyVDEzMDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZDE0NDg2YWRmNDY1YWU5YTllMWU0OWRhZWZmNjE4Y2ViODZjMWFkOGU5ZTczNTZkNGZiMmI1ZDEzZTk2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NaSZrfPd0OR_i4hLK7r5u1QIsFCEIzOUxMrBcSz1VlQ">
> Or am I doing it wrong?

Here’s an improved version of your comment with better grammar, structure, and clarity:

---

Hi @vzanfelici,

I may not have a direct resolution for your issue, but here are some pointers that might guide you in the right direction:

1. It seems the database file is being created within the simulator and is not shared with the host machine. ref:

   * [https://github.com/expo/expo/issues/32301](https://github.com/expo/expo/issues/32301)
   * [https://github.com/expo/expo/issues/4537](https://github.com/expo/expo/issues/4537)

2. **Project Dependencies:**

   ```json
   {
     "dependencies": {
       "@bottom-tabs/react-navigation": "^0.9.1",
       "@clerk/clerk-expo": "^2.11.3",
       "@expo/vector-icons": "^14.1.0",
       "@react-navigation/bottom-tabs": "^7.3.10",
       "@react-navigation/elements": "^2.3.8",
       "@react-navigation/native": "^7.1.6",
       "@sentry/react-native": "^6.13.1",
       "babel-plugin-inline-import": "^3.0.0",
       "date-fns": "^4.1.0",
       "drizzle-orm": "^0.43.1",
       "expo": "~53.0.9",
       "expo-blur": "~14.1.4",
       "expo-build-properties": "~0.14.6",
       "expo-constants": "~17.1.6",
       "expo-dev-client": "~5.1.8",
       "expo-font": "~13.3.1",
       "expo-haptics": "~14.1.4",
       "expo-image": "~2.1.7",
       "expo-linking": "~7.1.5",
       "expo-router": "~5.0.6",
       "expo-secure-store": "^14.2.3",
       "expo-splash-screen": "~0.30.8",
       "expo-sqlite": "~15.2.9",
       "expo-status-bar": "~2.2.3",
       "expo-symbols": "~0.4.4",
       "expo-system-ui": "~5.0.7",
       "expo-web-browser": "~14.1.6",
       "react": "19.0.0",
       "react-dom": "19.0.0",
       "react-native": "0.79.2",
       "react-native-bottom-tabs": "^0.9.1",
       "react-native-bouncy-checkbox": "3.0.5",
       "react-native-gesture-handler": "~2.24.0",
       "react-native-reanimated": "~3.17.4",
       "react-native-safe-area-context": "5.4.0",
       "react-native-screens": "~4.10.0",
       "react-native-web": "~0.20.0",
       "react-native-webview": "13.13.5"
     },
     "devDependencies": {
       "@babel/core": "^7.25.2",
       "@types/react": "~19.0.10",
       "drizzle-kit": "^0.31.1",
       "eslint": "^9.25.0",
       "eslint-config-expo": "~9.2.0",
       "typescript": "~5.8.3"
     }
   }
   ```

3. **iOS Simulator Version:**
   The simulator is running iOS 17.5.

---

### Comments

This issue has been reported in earlier versions and was resolved by updating the SDK. It appears to be an environment-related problem.
Here are some steps I suggest:

* Verify the versions of Expo and the iOS simulator.
* Update them if necessary.
* Build a fresh development build (not using Expo Go).

hope this helps!

**Comment by itsjatinnagar** [comment]
Those who are still facing the issue with the plugin. I have modified the plugin, it's working but have a very basic UI and functionality. Maybe we all can work on that.

**Comment by JamesBream** [comment]
> Those who are still facing the issue with the plugin. I have modified the plugin, it's working but have a very basic UI and functionality. Maybe we all can work on that.

@itsjatinnagar Could you share the modifications you've made to get it working?

**Comment by itsjatinnagar** [comment]
https://npmjs.com/package/expo-sqlite-devtools

I have created this package, please try that out.

**Comment by LaurentBonnot** [comment]
Any news about that?

**Comment by storm345s** [comment]
Hi!

Maybe i'm late, but better late like never...

I had the same issue after update my expo sdk from v52 to v53, after search a bit, i found that was a compatibility issue, so ensure you are using the properly version of drizzle studio to your expo sdk version or expo-sqlite version.

In my case, with expo sdk 53 and expo-sqlite 15.2.13, the properly drizzle studio version is the 0.2.0.

(works for me on google chrome and edge, didn't try on firefox or safari)

Regards

**Comment by narmistar** [comment]
For users on Expo SDK 53, make sure your Drizzle dependencies are up to date:
```
"drizzle-orm": "^0.44.5",
"expo-drizzle-studio-plugin": "^0.2.0",
"drizzle-kit": "^0.31.4"
```

**Comment by nonoray** [comment]
Is Drizzle Studio broken on Expo SDK 54 for anyone else? 
Mine is stuck loading forever.

Here are the versions I'm on:

```
"expo": "~54.0.32",  
"drizzle-orm": "^0.45.1",  
"expo-drizzle-studio-plugin": "^0.2.1",  
"drizzle-kit": "^0.31.8",
"expo-sqlite": "^16.0.10"
```

**Comment by AlwaysDreamingBig** [comment]
@nonoray Yo! Yeah I think there is an issue with the SDK 54,  my Drizzle Studio is also stuck loading forever even tho it was working with the latest versions of SDK 53.

Thought I was doing something wrong XD (the same thing...)

**Comment by itsjatinnagar** [comment]
Hi @nonoray, @AlwaysDreamingBig, mean time you can use this plugin.

https://npmjs.com/package/expo-sqlite-devtools
